// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsc0c8Iy-qdJ3kXH3clr6s56YmRcf0gI',
    appId: '1:1046131795703:web:436e39e709b564ea0d55f2',
    messagingSenderId: '1046131795703',
    projectId: 'blaprojectw7',
    authDomain: 'blaprojectw7.firebaseapp.com',
    storageBucket: 'blaprojectw7.firebasestorage.app',
    measurementId: 'G-RPPRV25ZC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHCM5yBV7UkjlNkqBRmmZuFIPplRlvKoA',
    appId: '1:1046131795703:android:6a5080f63b14b2730d55f2',
    messagingSenderId: '1046131795703',
    projectId: 'blaprojectw7',
    storageBucket: 'blaprojectw7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIFjlzGJMdmr2Bq_je7k-UIfN1SInZAr8',
    appId: '1:1046131795703:ios:b24e50bf7afac5ec0d55f2',
    messagingSenderId: '1046131795703',
    projectId: 'blaprojectw7',
    storageBucket: 'blaprojectw7.firebasestorage.app',
    iosBundleId: 'com.example.week3BlablaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIFjlzGJMdmr2Bq_je7k-UIfN1SInZAr8',
    appId: '1:1046131795703:ios:b24e50bf7afac5ec0d55f2',
    messagingSenderId: '1046131795703',
    projectId: 'blaprojectw7',
    storageBucket: 'blaprojectw7.firebasestorage.app',
    iosBundleId: 'com.example.week3BlablaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADsc0c8Iy-qdJ3kXH3clr6s56YmRcf0gI',
    appId: '1:1046131795703:web:4531cd6e1c2874e80d55f2',
    messagingSenderId: '1046131795703',
    projectId: 'blaprojectw7',
    authDomain: 'blaprojectw7.firebaseapp.com',
    storageBucket: 'blaprojectw7.firebasestorage.app',
    measurementId: 'G-J79VG4BX6B',
  );
}
